apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: master
  name: master
  namespace: gleamold
spec:
  replicas: 1
  selector:
    matchLabels:
      service: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: master
    spec:
      containers:
      - name: master
        image: chrislusf/gleamold
        ports:
        - containerPort: 45326
          protocol: TCP
        args:
          - "master"
